### ISSUE TITLE
Subutai installation page has some errors on Firefox browser

### ISSUE THREAD

**Issue by bkukanov** [subutai-io/website#108]
![screenshot from 2017-08-29 09 32 47](https://user-images.githubusercontent.com/11937839/29803395-4968dea2-8c9d-11e7-90a6-346fd6b441dd.png)
![screenshot from 2017-08-29 09 32 33](https://user-images.githubusercontent.com/11937839/29803396-4dae3de0-8c9d-11e7-9ecc-237259c673c1.png)

**Comment by crioto** [comment]
Same for me on Firefox on Ubuntu and MacOS
