### ISSUE TITLE
Add the Subutai FOSS Contribution Program page

### ISSUE THREAD

**Issue by akarasulu** [subutai-io/website#119]
Need to explain how the contribution program works and should reference another page on earning goodwill and another page which explains how goodwill works.

[Subutai FOSS Contribution Program]( https://subutai.io/helping-the-good-guys.html)

**Comment by efeefe** [comment]
was this page intentionally removed from the website @akarasulu ?

**Comment by akarasulu** [comment]
OMG he removed it again (face to palm). We need to get this back at that URL. @eemilov2501 put this URL back ASAP.

**Comment by akarasulu** [comment]
@efeefe this is the 2nd time it was removed by accident by @emilov2501. See this commit where I corrected the breakage: https://github.com/subutai-io/website/commit/a04ec866c0bbdc2babb93861f706cec22ae14f84
