### ISSUE TITLE
Add Subutai terminology definition to the website

### ISSUE THREAD

**Issue by tzununbekov** [subutai-io/website#150]
Currently, our installation page uses many Subutai-specific and technical terms (especially in Russian version), such as peer, hypervisor, sandbox, etc. without any definition of them. Regular user simply won't understand our ideas, so we must give short and clear description for those terms. 
Popup references are probably the best way to do it:
![screenshot from 2017-09-07 12-13-26](https://user-images.githubusercontent.com/13515865/30148618-15bea160-93c6-11e7-8706-a48946736753.png)

**Comment by efeefe** [comment]
reorganizing all websites, will drop this issue as well.
