### ISSUE TITLE
Missing part of the installation page in Firefox

### ISSUE THREAD

**Issue by crioto** [subutai-io/website#185]
When opening it for the first time it looks like this:

========================================

![screenshot-2017-9-19 subutai](https://user-images.githubusercontent.com/671147/30603686-18771e28-9d8a-11e7-8eb5-d240cac54907.png)

========================================

Clicking on any OS name reveals the full instructions:

========================================

![screenshot-2017-9-19 subutai 1](https://user-images.githubusercontent.com/671147/30603694-252d6898-9d8a-11e7-8897-0e4b722495fc.png)

**Comment by tjamakeev** [comment]
fixed
