### ISSUE TITLE
Section for pictures / gallery - subut.ai 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/website#214]
We need one more section that could be called : `Timeline`
On that section we need to store our pictures as albums: 
Like every album is an event, and it should be able to be named, for example: 
Conference - Brasil 15.10.2017 and etc..
_________________________________________________
Pictures to store 
- Pictures from conferences 
- Pictures from the office
- all sort of timeline photos 

This section should only consist of pictures with comments on them, like : 
This and that conference - tags: Names 
____________________________________________________
Examples: 
1. https://www.juicebox.net/demos/lite/full/
2. https://www.juicebox.net/demos/lite/embedded/

**Comment by efeefe** [comment]
Is that on the website or blog?
