### ISSUE TITLE
Update router image

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/website#248]

**Comment by bkukanov** [comment]
Here is link https://skfb.ly/696tS for router 2.0, will try to find better quality converter

**Comment by akylbekesenaliev** [comment]
I guess we should wait until you find better converter then @bkukanov , or should we proceed with this @akarasulu ?

**Comment by bkukanov** [comment]
@akylbekesenaliev and @eemilov2501 the file is updated, please change the link

**Comment by akylbekesenaliev** [comment]
@bkukanov thanks bro, link is updated
