### ISSUE TITLE
Booyakasha! word should be pointed with a link 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/website#274]
![image](https://user-images.githubusercontent.com/17665678/32047082-bca3ee10-ba66-11e7-973c-74fba1cb1e26.png)
Booyakasha! word should be pointed with a link  to: 
https://www.youtube.com/watch?v=WvMR6FT_ql0

**Comment by eemilov2501** [comment]
accept

**Comment by akarasulu** [comment]
Just delete the buyakasha word I was messing around. It's a joke. Just remove it.
