### ISSUE TITLE
Need to add a question line with How can I help and link it

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/website#276]
![image](https://user-images.githubusercontent.com/17665678/32047178-f90f94da-ba66-11e7-84b1-417a76a7cf8b.png)
Need to add a question line with How can I help and link it to:
https://subutai.io/help_us_out.htm
Like this: 
![image](https://user-images.githubusercontent.com/17665678/32047241-2549f93c-ba67-11e7-860f-a1bb75b4291e.png)

**Comment by eemilov2501** [comment]
accept
