### ISSUE TITLE
Update the FAQ text 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/website#279]
https://docs.google.com/a/optimal-dynamics.com/document/d/1P9Azjf2k-sXAeAl6_vpv4qHOD8PQYSBd7TLlbmQhQ04/edit?usp=sharing
![image](https://user-images.githubusercontent.com/17665678/32047917-53beb9ae-ba69-11e7-98ea-b1e3aae1655e.png)

**Comment by efeefe** [comment]
Dropping the issue, soon there will be a readthedocs instance with docs for all our projects.
