### ISSUE TITLE
Change the color of the Getting started button 

### ISSUE THREAD

**Issue by akylbekesenaliev** [subutai-io/website#297]
![image](https://user-images.githubusercontent.com/17665678/32217048-f790bfec-be50-11e7-822f-9a8ab45262ad.png)
We need to change the color of the Getting Started page because its color overflows with the background color and its kinda hard to notice the button.

**Comment by josealbertorodriguesjunior** [comment]
@eemilov2501 i assigned @jeehmilena right now to do that. Some idea about which color or opacity level must to be used to fix this overflow?

**Comment by efeefe** [comment]
This one may be already solved. Is it, @eemilov2501 ?

**Comment by eemilov2501** [comment]
to do this task, I used the background on the main page and made fixed position, but you can suggestions your ideas
