### ISSUE TITLE
Fork the weblog to a separate repository

### ISSUE THREAD

**Issue by efeefe** [subutai-io/website#302]
The weblog could benefit from being in a different repo with its own code, issues and tracking.

**Comment by eemilov2501** [comment]
our weblog dont have repo, because that doing on https://wordpress.com/

**Comment by efeefe** [comment]
Got it, I wasn't aware.

**Comment by efeefe** [comment]
Got it, I wasn't aware.

**Comment by efeefe** [comment]
Got it, I wasn't aware.

**Comment by efeefe** [comment]
Got it, I wasn't aware.
