### ISSUE TITLE
Comments on subutai's website, social networks and communication tools

### ISSUE THREAD

**Issue by efeefe** [subutai-io/website#330]
We're planning to revamp subutai's website, social networks and communication tools, and would like to have everyone's comments on what is missing, what is redundant and what could be done differently.

**Comment by neilspink** [comment]
It would be nice to have a button to navigate to the hub more quickly from the subutai.io homepage. Every time I want to get to the war room, I have to dig into "getting started" pages to find it.

**Comment by josealbertorodriguesjunior** [comment]
Explicit information that the subutai is open source, since this is only made explicit in the last block of the site

**Comment by jeehmilena** [comment]
**Some ideas about website**

Starting with home i guess in header should contain the principal information about the product for example: subtai is opens source, talking superficialy about subutai, subutai hub and subutai router among other principal information whether in format static or slider for example.  Another idea is about the structures, I think it should be a sequence of blocks started by "Getting starting", "A new way to think about clouds and devices attached to them", "social cloud computing" and finally the footer.

The internal pages I think maybe lighter, containing more images, restructured content or things like that.

**Comment by neilspink** [comment]
Not sure if these go towards your question and are what you want to hear:
- The tutorials have no meaning for someone new to Subutai. The tasks being shown are not described at all. The first video shows "Cross peer environment creation" with a registration process but suddenly at the end of the build at 1:07 minute shows unregistered. I suggest no music, just simple narration to explain. 
- One end to end example showing how you could use Subutai would be great. 
- The HUB user guide feature is really cool but quickly gets annoying. I know where the on/off button is, in the settings but maybe it would be less frustrating to have an off button in the little dialog popup.

**Comment by efeefe** [comment]
Thanks everyone for the feedback, we'll incorporate in the coming versions of our websites.

**Comment by efeefe** [comment]
@neilspink do you mean a button pointing to https://hub.subut.ai/ ? Don't you think users already registered will realise there's a dedicated URL to that? Or you're suggesting something else?

Re: https://github.com/subutai-io/website/issues/330#issuecomment-346342292

**Comment by neilspink** [comment]
People can't participate in the "war room", if the link is hidden somewhere
in the tutorials.

It might also be easier to find under the URL https://hub.subutai.io. The
current URL https://hub.subut.ai/  looks like a pishing URL.

**Comment by efeefe** [comment]
Thank everyone for the feedback. Closing the issue for now.
