### ISSUE TITLE
Link broken in Google Results

### ISSUE THREAD

**Issue by josealbertorodriguesjunior** [subutai-io/website#336]
In the results of google the link that points to  subutai social is broken. [This Link](https://subutai.io/first-launch.html)  results in a 404 error

![captura de tela de 2017-12-02 00-38-29](https://user-images.githubusercontent.com/8875485/33510900-3016876e-d6f9-11e7-8b29-a9f5e7bb2e7c.png)

![captura de tela de 2017-12-02 00-46-49](https://user-images.githubusercontent.com/8875485/33510962-57ee8894-d6fa-11e7-8c1e-ace5a205a106.png)

**Comment by josealbertorodriguesjunior** [comment]
I can't find where this link is located into subutai website. I found this link when i was looking for subutai console in the google searches

**Comment by eemilov2501** [comment]
this link perhaps from old the website source, on current website this link looking https://subutai.io/install/fiest-launch.html, this bug connected with SEO optimitzation, google bots  must check indexing website.

**Comment by eemilov2501** [comment]
I create isuues for SEO optimization, what tools for need to website...
