### ISSUE TITLE
Enable SEO optimizations

### ISSUE THREAD

**Issue by eemilov2501** [subutai-io/website#337]
1. Google Analytics account
2. Google Analytics source code
3. Google Search Console settings
3. Unique heading and description for Google search
4. Unique share heading and description for facebook, linkendin...
5. Key words

**Comment by josealbertorodriguesjunior** [comment]
Exists an email to use in google analytics account?

**Comment by eemilov2501** [comment]
yeap, i can share last pass for subtutai acc.

**Comment by eemilov2501** [comment]
![screenshot from 2017-12-08 14-59-31](https://user-images.githubusercontent.com/32386104/33758452-7f3243a4-dc28-11e7-904f-27700de83eb6.png)
i added tracking code for every page

**Comment by eemilov2501** [comment]
on a little begins to be indexed pages
![screenshot from 2017-12-08 15-03-03](https://user-images.githubusercontent.com/32386104/33758605-128bfe24-dc29-11e7-90b4-00f7deb84b69.png)

**Comment by efeefe** [comment]
Done then, @eemilov2501 ?

**Comment by eemilov2501** [comment]
yeap @efeefe
