### ISSUE TITLE
Daemon is misspelled on install page

### ISSUE THREAD

**Issue by efeefe** [subutai-io/website#338]
On [Subutai's install page](https://subutai.io/install/index.html), "Download Subutai" section, the name of the software is spelled "Deamon" instead of "Daemon" both in Mac OS and Linux tabs.

**Comment by eemilov2501** [comment]
ok, thanks man, just i say testers checked all pages on subutai.io, can i give you source code old website and you checked contents?

**Comment by akarasulu** [comment]
@efeefe Feel free to make such changes yourself! Might be faster and less traffic to talk and coordinate.

**Comment by efeefe** [comment]
Now we have access to the source code ;)
