### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by efeefe** [subutai-io/website#339]
It seems the repository has only the compiled HTML files. Is the source code published anywhere? How can changes be made? is there any documentation on the source code? (README is obsolete) @eemilov2501

**Comment by eemilov2501** [comment]
Yes, i create special branch for this, https://github.com/subutai-io/website/tree/gulp , i say @josealbertorodriguesjunior how installed is it

**Comment by akarasulu** [comment]
Issue corrections.

**Comment by eemilov2501** [comment]
I set up Cron job for my source code, no master branch is stable
