### ISSUE TITLE
Video doesn't work on website

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/website#346]
"Creating and Installing PGP Keys video" doesn't work on this page https://subutai.io/install/
![untitled1](https://user-images.githubusercontent.com/34295807/33792492-af49c64a-dccb-11e7-9242-300f981a6e74.png)

**Comment by eemilov2501** [comment]
@ibragim13kz @efeefe pls check subutai account in youtube

**Comment by efeefe** [comment]
It looks like the page is pointing to https://www.youtube.com/watch?v=POxi7oyjoE, but the right link of the video is https://www.youtube.com/watch?v=-POxi7oyjoE (with the "-" on the video code).

**Comment by eemilov2501** [comment]
ok, ill now change thats bugs, before that link be worked

**Comment by ibragim13kz** [comment]
Fixed.
