### ISSUE TITLE
Add copyright block in all Getting Started Pages

### ISSUE THREAD

**Issue by eemilov2501** [subutai-io/website#349]
we need copyright block for Getting Started Page, before it this you need think up to design with @jeehmilena and going to all page, that connected with getting started page
![screenshot-2017-12-11 subutai](https://user-images.githubusercontent.com/32386104/33830370-17f2e590-de9e-11e7-9a54-726c1592a082.png)
![fireshot capture 007 - getting started - https___subutai io_install_index html](https://user-images.githubusercontent.com/32386104/33830401-39e2e38a-de9e-11e7-8086-35384f967a0d.png)

**Comment by josealbertorodriguesjunior** [comment]
@eemilov2501 put the same homepage copyright block into getting started page?

**Comment by eemilov2501** [comment]
this is 2 screenshots, 1 screen is example, but that design to black we need also design to getting started page, and yes all pages for install pages. There are Browse plugin, First Launch etc.

**Comment by eemilov2501** [comment]
need put down

**Comment by jeehmilena** [comment]
@eemilov2501 the visual identity of the footer will be the same as the home?

**Comment by eemilov2501** [comment]
@jeehmilena yeap, change only background black to white
