### ISSUE TITLE
Quick start instructions

### ISSUE THREAD

**Issue by neil-spink-clouded-ch** [subutai-io/website#364]
Installation steps of typical person might be; download p2p and tray, register on hub, try to create an environment. There are some gaps;

1. Subutai E2E plugin - no information is provided that this is a chrome plugin and also no link. If you do not install and create the pgp key, then during environment creation, the hub takes you to the account page where you can upload the pgp finger print, there is no information here to help users. Perhaps here a user guide pop-up could help.

2. Environment creation assumes you have a peer or selected some a favorites. The step of choosing peers would be helpful.

**Comment by neil-spink-clouded-ch** [comment]
3. Creating your first environment, you need to create an SSH key in the tray. Also then you need to upload it too.

**Comment by neil-spink-clouded-ch** [comment]
4. A section to show how you SSH in would also be helpful.

**Comment by efeefe** [comment]
Dear @neil-spink-clouded-ch , thanks for your feedback. We are right now cooking great news regarding our documentation. Soon enough there will be a complete set of doc materials to every part of Subutai, and we will make sure to incorporate your suggestions. We'll let you know on Subutai-io slack.

**Comment by neil-spink-clouded-ch** [comment]
You may want to close this issue.
