### ISSUE TITLE
Outadated year at footer of subutai/optdyn websites

### ISSUE THREAD

**Issue by josealbertorodriguesjunior** [subutai-io/website#372]
![wrong year](https://user-images.githubusercontent.com/8875485/35565923-a6e29c30-05a6-11e8-993e-ce07f1942cf5.png)

The year located on footer of all our website is outdated

**Comment by eemilov2501** [comment]
i fixed, pls asap fix on blog @jeehmilena

**Comment by josealbertorodriguesjunior** [comment]
@eemilov2501 exists an alternate way to do that automatically with JS?

**Comment by jeehmilena** [comment]
@emilov2501 done on blog

**Comment by akarasulu** [comment]
@eemilov2501 @josealbertorodriguesjunior gave you a great idea:

> @eemilov2501 can you resolve it automatically with JS? Like ```(new Date()).getFullYear()``` 

@josealbertorodriguesjunior Might be easier to just this to the new website.

**Comment by josealbertorodriguesjunior** [comment]
@eemilov2501 I opened a pull request to solve this question using JS to get the year automatically
