### ISSUE TITLE
Router image in slider is cut, looks not pretty

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/website#410]
Currently we have cut image of blockchain router in slider on subutai.io. IMHO, it will look prettier if we put full image of the router there, not cut:

![screenshot at 2018-03-17 11-48-06](https://user-images.githubusercontent.com/33647491/37552137-20c2cc36-29d9-11e8-84de-9582c0ead2c9.png)

**Comment by fernandoted** [comment]
no more slider
