### ISSUE TITLE
Documentation page disappears from menu "resources" if user is already on documentation page

### ISSUE THREAD

**Issue by amol4anoff** [subutai-io/website#411]
Reproduce: go to subutai.io -> resources ->documentation. Once you are on documentation page, click resources again and find that documentation page absents. But it should be there.

![Screenshot from 2018-03-20 15-50-24.png](https://images.zenhubusercontent.com/5a0a77ce8a75884b90874c56/a7e9b78a-6569-41d8-a15c-5322cbcb6962)

![Screenshot from 2018-03-20 15-51-30.png](https://images.zenhubusercontent.com/5a0a77ce8a75884b90874c56/dfba51f3-af26-4536-acce-929a5bdb3174)

**Comment by efeefe** [comment]
Good catch. I've added the missing link (plus the one to Bazaar, also absent from docs til now). Next time RTD HTML is generated, it will be solved.
