### ISSUE TITLE
Subutai.io Homepage - KHAN section: Download PDF section 

### ISSUE THREAD

**Issue by Khudairi** [subutai-io/website#417]
Q: is there an anchor link to this section?

1) Change the copy in the button to say “Download PDF” (keep linked to existing PDF). Link to the v0.7 version of the doc in English.

2) Add second (exact) button to the right and change the copy in the button to say the Russian equivalent of “Download PDF” (“скачать PDF”? --please confirm with Shahrizadeh). Link to the v0.7 version of the doc in Russian.

3) Add third (exact) button to the right of that and change the copy in the button to say the Brazilian Portuguese equivalent of “Download PDF” --please work with Felipe ffonseca@optimal-dynamics.com on this. Link to the v0.7 version of the doc in Brazilian Portuguese.

NOTE: there is a Turkish version in development (possibly coming next week), so please don't make the link buttons too large.

**Comment by efeefe** [comment]
![image](https://user-images.githubusercontent.com/119052/39519538-861e639c-4ddd-11e8-9bf2-c5a071baa208.png)

**Comment by efeefe** [comment]
Done.
