### ISSUE TITLE
PRIORITY: upload OptDyn press release at 2PM/1400 Bishkek on 3 May 2018

### ISSUE THREAD

**Issue by Khudairi** [subutai-io/website#423]
Please follow the format at https://optdyn.com/press.html to list the press release

The format for the press release itself should look like https://optdyn.com/press-latam-campaign.html

The content is at https://docs.google.com/document/d/1rjuBAe-ec3qIcS5CWDTmH8B_ROxkWCj2d7WGwOzx2GI/edit?usp=sharing

Photos are attached here
![mou pti and optdyn 2](https://user-images.githubusercontent.com/31386124/39559115-da742ac4-4e61-11e8-9449-3531283d24b1.jpg)
![mou pti and optdyn](https://user-images.githubusercontent.com/31386124/39559116-da881fa2-4e61-11e8-8db7-e5b2f7f79312.jpg)

**Comment by samsonbek** [comment]
Done.
