### ISSUE TITLE
After pushing on buttons for download packages page is scrolling up and the down

### ISSUE THREAD

**Issue by AlinaPenkina** [subutai-io/website#432]
Download page needs to be static for each OS.
Now if user pushes button for download some package, page firstly scrolling to top of page and then scrolls to installers.
![image.png](https://images.zenhubusercontent.com/5a27a7008a75884b908a0e36/775488e8-d1d0-4cb8-98b8-29627e7915e9)

**Comment by fernandoted** [comment]
fixed
