### ISSUE TITLE
There are no robots.txt  and sitemap in website.

### ISSUE THREAD

**Issue by satarovaAziza** [subutai-io/website#447]
During checking the website with `` https://suite.seotesteronline.com`` Couldn't find following files :

![robot.txt.png](https://images.zenhubusercontent.com/5b0e5b9dc7faeb213bec8766/50c8d1ef-4828-4637-be98-c0c63d629370)

**Comment by fernandoted** [comment]
robots and sitemap included
<img width="1244" alt="screen shot 2018-09-11 at 1 51 17 pm" src="https://user-images.githubusercontent.com/7802029/45374937-efbd1380-b5c9-11e8-8afc-20ae66c94390.png">
