### ISSUE TITLE
URGENT: Revise optdyn.com home page 

### ISSUE THREAD

**Issue by Khudairi** [subutai-io/website#463]
Please follow instructions at Website streamlining doc https://docs.google.com/document/d/1QDcbqMIwLAUCpFJZsOLRoyqgw5kRyuWdp8YwbKmMUBM/edit?usp=sharing

Summary:
1) remove current homepage copy and place in new Website section
2) add new summary and embed 2 videos
3) add link to subutai.io

**Comment by fernandoted** [comment]
done
