### ISSUE TITLE
Please add snap install documentation

### ISSUE THREAD

**Issue by flexiondotorg** [subutai-io/website#89]
Hi,

I see you published a Subutai snap in the beta and edge channels of the snap store! :-)

Could you please update you installation instructions to include a section for installing snaps. For example:

---
Install subutai in seconds on [Ubuntu and other snap supported Linux distributions](https://snapcraft.io/docs/core/install) with:

    snap install subutai --devmode --beta

Installing a snap is very quick. Snaps are secure. They are isolated with all of their dependencies. Snaps also auto update when a new version is released.

**Comment by soffokl** [comment]
It's done here: https://subutai.io/installation.html
